# -*- coding: utf-8 -*-
"""Final Thesis Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCwUBQMlcLV86qU51Ey-ZWHXPa-hrSV6

#**SECTION 1: Introduction**
##**1.1 Overview of the Problem**
Water is one of the most essential resources for sustaining agriculture, yet inefficient irrigation practices often lead to waste, poor crop health, and unsustainable water consumption. The need for practical and efficient ways to manage water has become more evident. Innovative systems that can simplify plant care while conserving resources are timely and relevant. By understanding the importance of efficient watering and the consequence of wasteful practices, individuals can better appreciate the role of technology and mindful water use in building a more sustainable future.

##**1.2 Solution**

In order to contribute to addressing these challenges, this study focuses on an investigation into algorithmic-driven irrigation systems, namely **threshold-based, rules-based, and optimization-based systems**, to understand their effectiveness in optimizing water use.

##**1.3 Real-World Significance**
* Promotes efficient water use by reducing unnecessary irrigation and minimizing waste
* Supports sustainable agriculture and contributes to addressing water scarcity issues, especially in agriculture-dependent regions like the Philippines
* Helps improve crop health and yield through more consistent soil moisture management
* Demonstrates how algorithmic decision-making can be applied to real-world problems
* Serves as a foundation for future improvements in smart irrigation and agricultural technology

#**SECTION 2: Dataset Description**
##**2.1 About the Data Set**

The authors used the dataset, *“Smart Farming Sensor Data for Yield Prediction”* authored by Atharva Sundakar in April 2025.

##**2.1 Structure and Preprocessing**

**No. of Entries:** 500

**Details of features to be used:**
1. Crop type includes rice, wheat, cotton, soybean, and maize
2. Soil moisture content ranges from 10.2% to 45%
5. The recorded average temperature ranges from 15°C to 34.8°C.
6. Rainfall, measured in millimeters (mm), varies from 50.2 to 299.

#**SECTION 3: Requirements**
##**3.1 Installed Libraries and Frameworks**
To ensure the successful implementation of the models, several python libraries were utilized to support data manipulation and computations.

| Library | Version | Purpose |
| --------|---------|---------|
| Pandas | 3.0.0 |For data manipulation and analysis|
| NumPy | 2.4.0 |For numerical computing|
| matplotlib | 3.10.0 |For graphs|

**DATA SET IMPORT**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])
df.columns = df.columns.str.strip().str.lower()

df = df.rename(columns={
    "soil_moisture_%": "soil_moisture",
    "rainfall_mm": "rainfall",
    "temperature_c": "temperature"
})

df.head()

"""**DATA SET CLEANING**

Dropping unnecessary columns.
"""

column_drop = [
    "farm_id", "region", "soil_ph", "humidity_%", "sunlight_hours", "irrigation_type", "fertilizer_type", "pesticide_usage_ml", "sowing_date",
    "harvest_date", "total_days", "yield_kg_per_hectare", "sensor_id", "timestamp", "latitude", "longitude", "ndvi_index", "crop_disease_status",
]

df = df.drop(columns=column_drop, errors='ignore')
df["crop_type"] = df["crop_type"].str.strip().str.title()

print("DataFrame Columns:")
print(df.head())

"""#**SECTION 4: Simulation**
###**4.1 Simulation Setup**
Defining Constraints   -->    Creating Stress Model for Realism   -->   Simulations for each system   -->   Metrics

###**4.2 Defining Parameters and Constraints**
The parameters define the variables, thresholds, and environmental conditions necessary for the operation of the irrigation algorithms, while the constraints establish the limitations and assumptions applied throughout the simulation to ensure realistic and controlled behavior.

###**4.2.1 General Parameters**
These values controlled the duration of the experiment, soil moisture targets, evapotranspiration, rainfall contribution, uncertainty, and irrigation efficiency.
"""

DAYS = 28
SM_TARGET = 42
THRESHOLD = 35

ET = 2.0
RAIN_FACTOR = 0.005

NOISE_STD = 0.8
IRRIGATION_EFF = 0.90

"""
###**4.2.2 Evaluation Parameters**
These parameters define the soil moisture boundaries used to distinguish between dry stress, optimal moisture, and excessive water conditions."""

FC = 45
MAD = 35
OPT_LOW = 38
OPT_HIGH = 43

"""###**4.2.3 Crop Co-Efficients**
Crop coefficients were used to adjust reference evapotranspiration according to the water demand of each crop. The coefficient Kc represents the ratio between crop evapotranspiration and reference evapotranspiration. Crops with longer growing periods, or higher water demand were assigned higher coefficients, while crops with lower relative water demand were assigned lower coefficients.

The values were used as representative mid-season crop coefficients to allow the model to compare irrigation strategies under crop-specific water demand conditions.

These coefficients were treated as representative values, since actual Kc values can vary depending on crop growth stage, climate, soil conditions, and irrigation method.

"""

CROP_COEFFICIENTS = {
    "Rice": 1.30,     #highest water demand
    "Wheat": 0.95,    #lower demand compared to others
    "Cotton": 1.15,   #moderate water demand
    "Soybean": 1.05,  #moderate water demand
    "Maize": 1.20     #High ET during growth
}

"""###**4.2.4 Cost Parameters**
To have a rough idea of the practical applicability of the systems, the researchers also applied basic cost-benefit metrics. The water rates used are based on local utilities, while the electricity rates are based on Meralco averages. These are just generic irrigation pump assumptions to compare the relative efficiency and practicality of the different irrigation algorithms under simulated conditions.
"""

WATER_COST_PER_UNIT = 0.05   # pesos per irrigation unit
POWER_RATE = 12.0            # pesos per kWh
PUMP_POWER_KW = 0.5          # pump power
PUMP_HOURS_PER_UNIT = 0.02   # runtime per irrigation unit

"""###**4.3 Creating Stress Model for Realism**
These functions simulates whether a plant becomes stressed based on environmental conditions like soil moisture, drought history, excess water, and temperature.

**Parameters:**

sm - current soil moisture

drought_index - accumulated drought condition over time

water_excess - amount of overwatering or flooding

temperature - current temperature

base_risk - minimum/default stress chance (default = 5%)

"""

def stress_probability(sm, drought_index, water_excess, base_risk=0.05):

    dry_risk = max(0, (SM_TARGET - sm) / 10)

    wet_risk = max(0, (sm - FC) / 10)

    memory = np.tanh(drought_index / 2.5)

    p = (
        0.40 * dry_risk +
        0.20 * wet_risk +
        0.25 * memory +
        0.15 * water_excess +
        base_risk
    )

    p += np.random.normal(0, 0.03)

    return np.random.rand() < np.clip(p, 0.03, 0.85)

# WASTE FUNCTION
def waste_calc(sm_before, water):

    excess = max(0, (sm_before + water) - FC)

    waste = (
        excess * 0.7 +
        water * 0.04
    )

    return waste

# NOISE
def noisy(x):
    return x + np.random.normal(0, NOISE_STD)

"""###**4.4 Model Simulations**
####**4.4.1 Threshold-based Simulation**
**Equation for Threshold-based Irrigation:**

*Irrigation = {ON if SM < SM_threshold  ,OFF if SM ≥ SM_threshold*

Where:

SM = Current soil moisture (%)

SM_threshold = Predefined soil moisture threshold (%)

####**4.4.2 Rules-based Simulation**
The Rule-Based irrigation algorithm applies predefined IF–THEN conditions derived from farming knowledge.

*Irrigation = f(SM,R)*

{High | if SM =Low AND R= None

{Medium  | if SM=Medium AND R= Light

{Low  | if SM=High AND R = Heavy

*SM = Soil moisture*

*R = Rainfall*

####**4.4.3 Optimization-based Simulation**
**Equations for Optimization-Based Irrigation:**

min ΣI_t (t=1 to T)


**Subject to:**

SM_min ≤ SM_t ≤ SM_max

SM_(t+1) = SM_t + I_t + R_t - ET_t


**Where:**

*I_t = irrigation amount at time t*

*SM_t = soil moisture at time t*

*R_t = rainfall at time t*

*ET_t = water loss at time t*
"""

def run_model(mode="threshold", crop_type=None):

    if crop_type is None:
        crop_df = df.copy()
        crop_type = crop_df["crop_type"].iloc[0]
    else:
        crop_df = df[df["crop_type"] == crop_type].copy()

    if len(crop_df) == 0:
        raise ValueError(f"No records found for crop type: {crop_type}")

    Kc = CROP_COEFFICIENTS.get(crop_type, 1.00)

    sm = crop_df["soil_moisture"].iloc[0]

    drought_index = 0

    out = []

    for d in range(DAYS):

        row = crop_df.iloc[d % len(crop_df)]

        rain = row["rainfall"]

        ETo = ET + np.random.normal(0, 0.2)

        # Crop-specific evapotranspiration
        ETc = Kc * ETo

        sm_before = sm

        # THRESHOLD
        if mode == "threshold":

            if sm < THRESHOLD:
                water = 5
            else:
                water = 0

        # RULE-BASED
        elif mode == "rule":

            if sm < 32:
                water = 5.5

            elif sm < 38:
                water = 3.0

            else:
                water = 1.2

            water *= np.random.uniform(0.85, 1.15)

        # OPTIMIZATION
        elif mode == "opt":

          error = SM_TARGET - sm
          expected_rain_effect = rain * RAIN_FACTOR

          # optimization responds to crop-specific water demand
          water = (
              0.60 * error +
              0.40 * ETc -
              expected_rain_effect
          )

          # optimization conserves water when soil moisture is already near target
          if sm >= OPT_HIGH:
              water = 0

          elif sm >= SM_TARGET:
              water *= 0.20

          water += np.random.normal(0, 0.05)

          water = np.clip(water, 0, 3.5)


        # WATER DYNAMICS
        sm = (
            sm +
            water * IRRIGATION_EFF +
            rain * RAIN_FACTOR -
            ETc
        )

        sm = noisy(sm)

        sm = np.clip(sm, 0, 100)


        # MEMORY
        drought_index = (
            0.85 * drought_index +
            (1 if sm < MAD else 0)
        )

        # WATER EXCESS
        water_excess = max(0, (sm - FC) / 10)

        # STRESS
        stress = stress_probability(
            sm,
            drought_index,
            water_excess,
            base_risk=0.05
        )

        # WASTE
        waste = waste_calc(sm_before, water)

        out.append([
            d + 1,
            crop_type,
            Kc,
            ETo,
            ETc,
            sm,
            water,
            int(stress),
            waste
        ])

    return pd.DataFrame(
        out,
        columns=[
            "Day",
            "Crop",
            "Kc",
            "ETo",
            "ETc",
            "Soil_Moisture",
            "Irrigation",
            "Stress",
            "Waste"
        ]
    )

"""#**SECTION 5: Evaluation**
###**5.1 Evaluation Metrics**
The evaluation aims to assess and compare the system's performance in terms of:
| Metric | Definition | Goal |
|-|-|-|
| Water Use Efficiency | Number of Stable Days / Total Irrigation Water Applied | Maximize |
| Root Zone Stability | Percentage of time moisture stayed within the optimal root zone range over time | Maximize |
| Water Waste Index | Total water loss due to overwatering | Minimize |
| Irrigation Frequency | Number of times the system activated | The lower, the better |
| Stress Days | Number of days where moisture dropped below the Management Allowed Depletion (MAD) | Minimize |
"""

def evaluate_model(df_model):

    total_irrigation = df_model["Irrigation"].sum()

    # stable days
    stable_days = (
        (df_model["Soil_Moisture"] >= OPT_LOW) &
        (df_model["Soil_Moisture"] <= OPT_HIGH)
    ).sum()

    # WUE
    wue = stable_days / (total_irrigation + 1e-6)

    # Root Zone Stability
    root_zone_stability = stable_days / len(df_model)

    # Water Waste Index
    waste_index = (
        df_model["Waste"].sum() /
        (total_irrigation + 1e-6)
    )

    # Irrigation Frequency
    irrigation_frequency = (
        df_model["Irrigation"] > 1.0
    ).sum()

    # Stress Days
    stress_days = (
        df_model["Soil_Moisture"] < MAD
    ).sum()

    return {
        # eval metrics
        "WUE": round(wue, 3),
        "Root_Zone_Stability": round(root_zone_stability, 3),
        "Water_Waste_Index": round(waste_index, 3),
        "Irrigation_Frequency": int(irrigation_frequency),
        "Stress_Days": int(stress_days),
        # cost-benefit metrics
        "Water_Cost": round(water_cost, 2),
        "Energy_Cost": round(energy_cost, 2),
        "Total_Cost": round(total_cost, 2)
    }

"""###**5.2 Cost Metrics**
**Equations Used:**

WATER COST = TOTAL IRRIGATION x WATER_COST_PER_UNIT

ENERGY COST = (TOTAL IRRIGATION x PUMP HRS PER UNIT x PUMP POWER) x POWER RATE

TOTAL COST = WATER COST + ENERGY COST
"""

# WATER COST
    water_cost = total_irrigation * WATER_COST_PER_UNIT

    # ENERGY CONSUMPTION
    energy_used = (
    total_irrigation *
    PUMP_HOURS_PER_UNIT *
    PUMP_POWER_KW
    )

    # ENERGY COST
    energy_cost = energy_used * POWER_RATE

    # TOTAL OPERATIONAL COST
    total_cost = water_cost + energy_cost

"""###**5.3 Running 30 Simulations**
Because the simulation model includes random components, each treatment was evaluated over multiple simulation runs. The reported cost values represent the mean results across repeated trials, allowing comparison of the Threshold, Rule-Based, and Optimization methods under variable environmental conditions.
"""

all_simulation_summaries = []
all_daily_results_list = []


N_SIMULATIONS = 30

for sim in range(1, N_SIMULATIONS + 1):

    # makes the whole experiment reproducible
    np.random.seed(sim)

    all_results = []

    for crop in sorted(df["crop_type"].unique()):

        th_crop = run_model("threshold", crop)
        ru_crop = run_model("rule", crop)
        op_crop = run_model("opt", crop)

        th_crop["Model"] = "Threshold"
        ru_crop["Model"] = "Rule-Based"
        op_crop["Model"] = "Optimization"

        all_results.extend([th_crop, ru_crop, op_crop])

    results = pd.concat(all_results, ignore_index=True)
    results["Simulation"] = sim
    all_daily_results_list.append(results)

    summary_rows = []

    for crop in sorted(results["Crop"].unique()):

        for model in ["Threshold", "Rule-Based", "Optimization"]:

            model_df = results[
                (results["Crop"] == crop) &
                (results["Model"] == model)
            ]

            eval_result = evaluate_model(model_df)

            summary_rows.append([
                sim,
                crop,
                model,
                eval_result["WUE"],
                eval_result["Root_Zone_Stability"],
                eval_result["Water_Waste_Index"],
                eval_result["Irrigation_Frequency"],
                eval_result["Stress_Days"],
                eval_result["Water_Cost"],
                eval_result["Energy_Cost"],
                eval_result["Total_Cost"]
            ])

    sim_summary = pd.DataFrame(
        summary_rows,
        columns=[
          "Simulation",
          "Crop",
          "Model",
          "WUE",
          "Root_Zone_Stability",
          "Water_Waste_Index",
          "Irrigation_Frequency",
          "Stress_Days",
          "Water_Cost",
          "Energy_Cost",
          "Total_Cost"
      ]
    )

    all_simulation_summaries.append(sim_summary)
    all_daily_results = pd.concat(
      all_daily_results_list,
      ignore_index=True
    )

"""#**SECTION 6: Results & Analysis**
###**6.1 Comparison of Results**

**CROP-SPECIFIC EVALUATION**
"""

all_simulation_results = pd.concat(
    all_simulation_summaries,
    ignore_index=True
)

average_summary_by_crop_method = (
    all_simulation_results
    .groupby(["Crop", "Model"], as_index=False)
    .agg({
        "WUE": "mean",
        "Root_Zone_Stability": "mean",
        "Water_Waste_Index": "mean",
        "Irrigation_Frequency": "mean",
        "Stress_Days": "mean",
        "Water_Cost": "mean",
        "Energy_Cost": "mean",
        "Total_Cost": "mean"
    })
    .round(3)
)

average_summary_by_crop_method["Score"] = (
    average_summary_by_crop_method["WUE"] * 6 +
    average_summary_by_crop_method["Root_Zone_Stability"] * 5 -
    average_summary_by_crop_method["Water_Waste_Index"] * 6 -
    average_summary_by_crop_method["Irrigation_Frequency"] * 0.5 -
    average_summary_by_crop_method["Stress_Days"] * 3 -
    average_summary_by_crop_method["Total_Cost"] * 0.3
)

print("\n=== AVERAGE CROP-SPECIFIC EVALUATION ACROSS SIMULATIONS ===")
display(average_summary_by_crop_method)

best_overall = average_summary_by_crop_method.loc[
    average_summary_by_crop_method["Score"].idxmax()
]

print(
    "\nBEST OVERALL CROP-MODEL COMBINATION:",
    best_overall["Crop"],
    "-",
    best_overall["Model"]
)

"""Among all crop-model combinations, the **Wheat–Optimization** configuration achieved the highest overall score of **-1.2398**, indicating the most balanced performance. This could be explained by wheat having a lower Kc than rice and maize, making it easier to maintain its target moisture.

Crops with higher crop coefficient values, such as rice and maize, generally required more irrigation and incurred higher operational costs due to increased evapotranspiration demand. This indicates that crop-specific coefficients significantly influenced irrigation behavior within the simulation.

In terms of models, the **Rule-Based model** consistently maintained favorable soil moisture conditions across different crops, resulting in high root zone stability and reduced stress days. However, this performance came at the expense of increased irrigation frequency, water waste, and operational cost.

Meanwhile, the **Threshold-Based** model minimized irrigation cost and water waste by applying irrigation only when soil moisture fell below a fixed threshold. However, this conservative irrigation behavior frequently resulted in crop stress conditions, particularly for crops with higher evapotranspiration requirements.

Finally, the **Optimization-Based** model demonstrated balanced irrigation behavior by reducing unnecessary irrigation while maintaining acceptable soil moisture stability and operational cost. Compared to the Rule-Based model, the optimization approach achieved lower irrigation frequency and water waste while still preventing excessive crop stress in most scenarios.

**ALGORITHM-ONLY EVALUATION**
"""

all_simulation_results = pd.concat(
    all_simulation_summaries,
    ignore_index=True
)

average_summary_by_method = (
    all_simulation_results
    .groupby("Model", as_index=False)
    .agg({
        "WUE": "mean",
        "Root_Zone_Stability": "mean",
        "Water_Waste_Index": "mean",
        "Irrigation_Frequency": "mean",
        "Stress_Days": "mean",
        "Water_Cost": "mean",
        "Energy_Cost": "mean",
        "Total_Cost": "mean"
    })
    .round(3)
)

display(average_summary_by_method)

"""**Water Use Efficiency**

The results show that the **Optimization model** achieved the highest overall performance among the three irrigation strategies with a WUE score of **0.413**, indicating that it utilized water more effectively. In comparison, the **Threshold-Based model** recorded the lowest WUE at **0.076**, suggesting poor utilization of supplied water.

**Root Zone Stability**

In terms of Root Zone Stability, the **optimization-based model** also achieved the highest value at **0.717**, closely followed by the **rule-based model** at **0.611**. Higher root zone stability indicates that soil moisture was more consistently maintained within the desired range. The **Threshold-Based model** had the lowest stability at **0.114**, implying that soil moisture levels were more unstable.

**Water Waste Index, Irrigation Frequency, and Stress Days**

For Water Waste Index, the **Threshold-Based model** produced a low value at **0.4**, which suggests minimal water waste. However, this model also recorded **10** stress days, indicating that water conservation was achieved at the expense of optimal plant hydration. *This implies that the Threshold-Based approach may inadequately water crops when relying solely on fixed moisture thresholds.*

The **Rule-Based model** generated the highest Water Waste Index at **0.08** and the highest irrigation frequency at **28**. This indicates that although the model successfully prevented plant stress by having stress days of only **3**, it tended to apply excessive irrigation, leading to inefficient water use. *The frequent irrigation may have contributed to maintaining stable soil moisture conditions, but at the cost of increased water consumption.*

The Optimization model demonstrated a balance between water conservation and crop health. Its Water Waste Index, **0.04**, was similar to the Threshold-Based model, and significantly lower than the Rule-Based model while still maintaining **low** stress days. Additionally, its irrigation frequency at **22** was lower than the Rule-Based model, suggesting that *the optimization strategy was able to deliver water only when necessary while maintaining favorable soil conditions.*

**COST COMPARISON**
"""

cost_summary_by_method = (
    all_simulation_results
    .groupby("Model")
    .agg({
        "Water_Cost": ["mean", "std"],
        "Energy_Cost": ["mean", "std"],
        "Total_Cost": ["mean", "std"]
    })
    .round(2)
)

print("\n=== COST SUMMARY BY METHOD: MEAN AND STANDARD DEVIATION ===")
display(cost_summary_by_method)

"""Among the methods, the **Threshold-Based model** recorded the **lowest** overall cost at **₱8.68**, consisting of **₱2.55** in water cost and **₱6.13** in energy cost. Its lower operational cost can be attributed to its simple irrigation logic, where watering is only triggered once the soil moisture falls below a fixed threshold. However, while this approach is cost-efficient, it may not provide the most reliable irrigation performance since the system reacts only after moisture levels have already dropped below the acceptable range.

The **Rule-Based model** produced the **highest** total cost at **₱9.57**, with **₱2.82** allocated to water consumption and **₱6.76** to energy usage. This increase in cost is likely due to the model’s reliance on the predefined conditions designed to maintain soil moisture within safe levels. Although this improves adaptability and reduces the likelihood of crop stress, it also introduces greater operational expenses and potential water waste.

Meanwhile, the **Optimization model** achieved a total cost of **₱9.48,** which is slightly lower than the Rule-Based model but higher than the Threshold-Based model. The model consumed **₱2.79** in water cost and **₱6.69** in energy cost, indicating that it was able to reduce unnecessary irrigation while still maintaining adaptive decision-making capabilities. Unlike the other approaches, the Optimization model is able to effectively balance environmental inputs and soil moisture conditions to minimize resource consumption without compromising irrigation effectiveness.

###**6.2 Analysis of Results**

**CROP-SPECIFIC COMPARISON GRAPH**
"""

crop_opt_daily_avg = (
    all_daily_results[
        all_daily_results["Model"] == "Optimization"
    ]
    .groupby(["Crop", "Day"], as_index=False)["Soil_Moisture"]
    .mean()
)

plt.figure(figsize=(12,6))

for crop in sorted(crop_opt_daily_avg["Crop"].unique()):

    crop_data = crop_opt_daily_avg[
        crop_opt_daily_avg["Crop"] == crop
    ]

    plt.plot(
        crop_data["Day"],
        crop_data["Soil_Moisture"],
        label=f"{crop} - Optimization"
    )

plt.axhline(OPT_LOW, linestyle="--")
plt.axhline(OPT_HIGH, linestyle="--")

plt.xlabel("Day")
plt.ylabel("Average Soil Moisture Across 30 Simulations")
plt.title("Average Crop-Specific Soil Moisture: Optimization Method")
plt.legend()
plt.show()

"""The results show that the model successfully **adjusted irrigation behavior according to the moisture requirements of different crop types**.

Crops with higher water demand, such as rice, maintained higher initial moisture levels, while crops with lower water demand, such as wheat, remained relatively stable throughout the simulation period. Meanwhile, maize, cotton, and soybean exhibited gradual increases in soil moisture until reaching the target range.

Despite the differences in crop requirements, the Optimization model **consistently stabilized soil moisture within the acceptable threshold boundaries**, demonstrating its adaptability and balanced irrigation control performance.

The graph further validates the effectiveness of incorporating crop-specific coefficients into the optimization process, as the system was **able to regulate moisture levels differently depending on the irrigation needs of each crop while avoiding excessive fluctuations and over-irrigation**.

**ALGORITHM SOIL MOISTURE COMPARISON GRAPH**
"""

algo_daily_avg = (
    all_daily_results
    .groupby(["Model", "Day"], as_index=False)["Soil_Moisture"]
    .mean()
)

plt.figure(figsize=(12,6))

for model in ["Threshold", "Rule-Based", "Optimization"]:

    model_data = algo_daily_avg[
        algo_daily_avg["Model"] == model
    ]

    plt.plot(
        model_data["Day"],
        model_data["Soil_Moisture"],
        label=model
    )

plt.axhline(OPT_LOW, linestyle="--")
plt.axhline(OPT_HIGH, linestyle="--")

plt.xlabel("Day")
plt.ylabel("Average Soil Moisture Across Crops and 30 Simulations")
plt.title("Average Algorithm Soil Moisture Comparison Across 30 Simulations")
plt.legend()
plt.show()

"""* The **Threshold-Based model** exhibited lower and less adaptive moisture
regulation
* The **Rule-Based model** maintained consistently higher moisture levels at the expense of increased resource consumption.
* The **Optimization model** demonstrated stable convergence within the target moisture range while minimizing excessive irrigation, confirming its ability to balance water efficiency and crop moisture requirements across different crop types.

#**SECTION 7: Insights & Conclusions**
##**7.1 Findings**

The findings revealed that the **Optimization-Based model** achieved the highest Water Use Efficiency and Root Zone Stability while maintaining low stress days and a relatively low Water Waste Index. These results indicate that the optimization approach was able to effectively balance water conservation and crop health by applying irrigation only when necessary and adapting to changing soil moisture conditions.

In contrast, the **Threshold-Based model** demonstrated the lowest irrigation frequency and water waste, but it also resulted in plant stress days and poor soil moisture stability. This suggests that relying solely on fixed soil moisture thresholds may conserve water but may not consistently maintain suitable conditions for plant growth.

Meanwhile, the **Rule-Based model** successfully mitigated stress days and improved soil moisture stability; however, it required more frequent irrigation and produced the highest water waste index, indicating less efficient water management.

Furthermore, the incorporation of **crop-specific evapotranspiration coefficients** improved the realism and adaptability of the irrigation simulation by allowing the system to account for varying crop water requirements. The inclusion of simplified **cost-benefit metrics** also provided additional insight into the operational practicality of the irrigation models by estimating water and energy-related expenses under simulated conditions.  

##**7.2 Recommendations**

Future researchers may further enhance the system by integrating real-time sensor data, weather forecasting, machine learning techniques, and additional environmental factors to improve irrigation accuracy and adaptability in real-world agricultural settings.

#**SECTION 8: Documentation**
###**8.1 UI**
A Gradio-based web application hosted on Hugging Face was developed as a proof of concept to demonstrate model inference for the three irrigation scheduling algorithms. Gradio is chosen for its lightweight interface, browser accessibility, and seamless integration with Python-based frameworks, while Hugging Face enables free public sharing of the interactive application.

[IrrigationUI - HuggingFace](https://huggingface.co/spaces/ag-sxb/IrrigationUI)

###**8.2 AMA Paper**
For a more detailed documentation of our study, you may refer to the AMA format manuscript below:

[Manuscript](https://)

###**8.3 Proof of Concept**
The Github repository linked below serves as our official proof of concept.

[Github](https://github.com/aglseballos/Irrigation-System)
"""